title: aizentranza.github.io/accordion
author: Kinoshita Naoki
email: 'kinoshita_naoki@mail.goo.ne.jp'
url: https://aizentranza.github.io
baseurl: accordion
twitter_username: kinoshita_naoki
github_username: aizentranza
description: Accordion Sheet Music
theme: minima
